# Generated by Django 4.0.4 on 2022-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_curier_accepted_at_letter_currier_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='comment',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Izoh'),
        ),
    ]
